# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentnews',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
