# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_currentnews_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentnews',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 6, 24, 7, 30, 32, 525312, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
